#!/bin/bash
#PBS -N imineq-ee
#PBS -j oe
#PBS -l walltime=03:00:00:00
#PBS -l pmem=280mb
#PBS -l nodes=1:ppn=2
#PBS -V

# Job proper starts here

# Additional environment setting, if necessary
# export PATH=/some/dir/:$PATH
# run job ________________________
cd $PBS_O_WORKDIR 

# run job
./go.py
