#!/bin/bash
#PBS -N emineq
#PBS -j oe
#PBS -l walltime=03:00:00:00
#PBS -l pmem=270mb
#PBS -l nodes=1:ppn=4
#PBS -V

# Job proper starts here

# Additional environment setting, if necessary
# export PATH=/some/dir/:$PATH
# run job ________________________
cd $PBS_O_WORKDIR

# run job
./go.py
