#!/bin/bash
#PBS -N vmineq-le 
#PBS -j oe
#PBS -l walltime=03:00:00:00
#PBS -l pmem=480mb
#PBS -l nodes=4:ppn=1
# #PBS -M dmerz3@gatech.edu
#PBS -V

# Job proper starts here

# Additional environment setting, if necessary
# export PATH=/some/dir/:$PATH
# run job ________________________
cd $PBS_O_WORKDIR 

# run job
./go.py
